# Generated by Django 4.1.3 on 2022-11-21 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
